apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-example
  labels:
    release: prom
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: cluster-example
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
